PTraceback (most recent call last):
  File "refresh_pivot2.py", line 66, in <module>
    refresh_pivots(sys.argv[1])
  File "refresh_pivot2.py", line 53, in refresh_pivots
    pt.ChangePivotCache(cache)
  File "<COMObject <unknown>>", line 2, in ChangePivotCache
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', "This command requires at least two rows of source data. You cannot use the command on a selection in only one row. Try the following:\n\n• If you're using an advanced filter, select a range of cells that contains at least two rows of data. Then click the Advanced Filter command again.\n• If you're creating a PivotTable report or PivotChart report, type a cell reference or select a range that includes at least two rows of data.", 'xlmain11.chm', 0, -2147024809), None)
